version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-server
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timout: 300
      runas: ubuntu
