version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-server
hook:
  stop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
  setting:
    - location: scripts/setting.sh
      timout: 300
      runas: ubuntu
  start:
    - location: scripts/start.sh
      timout: 300
      runas: ubuntu
